remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache  
  - jekyll-sitemap

locale: "ru-RU"

title: "Страховой Брокер Скала"

logo: "/assets/images/logo.jpg"


description: ""

search: false

footer:
  links:[]
  
defaults:        
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      header:
        overlay_image: "/assets/images/mountains1.jpg"
        overlay_color: "#00f"

        
  - scope:
      path: "about"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "s_about"
        
  - scope:
      path: "services"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "s_services"
        
  - scope:
      path: "reinsurance"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "s_reinsurance"
        
  - scope:
      path: "partners"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "s_partners"            

